import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'You App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
       <head>
        <link rel='icon' href='/youapp.png' sizes="any"/>
      </head>
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}
